name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      image_tag: |
        latest
        1.14.0-bullseye-r2 # renovate: datasource=github-releases depName=tianon/gosu
        1.14.0-bullseye # renovate: datasource=github-releases depName=tianon/gosu
        1.14.0 # renovate: datasource=github-releases depName=tianon/gosu
        1.14
        1
    secrets: inherit
