name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      image_tag: 1.14.0-bullseye-r1
    secrets: inherit
