name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      image_tag: |
        latest
        1.16.0-bullseye-r1 # renovate: datasource=github-releases depName=tianon/gosu
        1.16.0-bullseye # renovate: datasource=github-releases depName=tianon/gosu
        1.16.0 # renovate: datasource=github-releases depName=tianon/gosu
        1.16
        1
    secrets: inherit
